[project]
name = "airquality"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "dash>=3.2.0",
  "fastapi>=0.116.1",
  "folium>=0.12",
  "geopandas>=1.1.2",
  "mapclassify>=2.10.0",
  "matplotlib>=3.10.8",
  "pandas>=3.0.0",
  "pydantic-settings>=2.0.0",
  "pyarrow>=17.0.0",
  "pyspark>=4.1.1",
  "requests>=2.32.5",
  "tensorboard>=2.20.0",
  "torch>=2.10.0",
  "torchvision>=0.24.1",
  "uvicorn>=0.35.0",
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu" },
]
torchvision = [
  { index = "pytorch-cpu" },
]

[[tool.mypy.overrides]]
module = ["joblib.*", "sklearn.*"]
follow_untyped_imports = true

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "mypy>=1.19.1",
    "ruff>=0.15.0",
    "types-requests>=2.32.4.20260107",  
    "pandas-stubs>=3.0.0.260204",  
]
